MaximeLEAU_affiliate_new:
    pattern:  /new
    defaults: { _controller: "MaximeLEAUJobeetBundle:Affiliate:new" }
    
MaximeLEAU_affiliate_create:
    pattern: /create
    defaults: { _controller: "MaximeLEAUJobeetBundle:Affiliate:create" }
    requirements: { _method: post }
    
MaximeLEAU_affiliate_wait:
    pattern: /wait
    defaults: { _controller: "MaximeLEAUJobeetBundle:Affiliate:wait" }