MaximeLEAU_job:
    path:     /
    defaults: { _controller: "MaximeLEAUJobeetBundle:Job:index" }

MaximeLEAU_job_show:
    pattern:  /{company}/{location}/{id}/{position}
    defaults: { _controller: "MaximeLEAUJobeetBundle:Job:show" }
    requirements:
        id:  \d+

MaximeLEAU_job_preview:
    pattern:  /{company}/{location}/{token}/{position}
    defaults: { _controller: "MaximeLEAUJobeetBundle:Job:preview" }
    requirements:
        token:  \w+

MaximeLEAU_job_new:
    path:     /new
    defaults: { _controller: "MaximeLEAUJobeetBundle:Job:new" }

MaximeLEAU_job_create:
    path:     /create
    defaults: { _controller: "MaximeLEAUJobeetBundle:Job:create" }
    methods:  POST

MaximeLEAU_job_edit:
    pattern:  /{token}/edit
    defaults: { _controller: "MaximeLEAUJobeetBundle:Job:edit" }

MaximeLEAU_job_update:
    pattern:  /{token}/update
    defaults: { _controller: "MaximeLEAUJobeetBundle:Job:update" }
    requirements: { _method: post|put }

MaximeLEAU_job_delete:
    pattern:  /{token}/delete
    defaults: { _controller: "MaximeLEAUJobeetBundle:Job:delete" }
    requirements: { _method: post|delete }
    
MaximeLEAU_job_publish:
    pattern:  /{token}/publish
    defaults: { _controller: "MaximeLEAUJobeetBundle:Job:publish" }
    requirements: { _method: post }
    
MaximeLEAU_job_extend:
    pattern:  /{token}/extend
    defaults: { _controller: "MaximeLEAUJobeetBundle:Job:extend" }
    requirements: { _method: post }

MaximeLEAU_job_search:
    pattern: /search
    defaults: { _controller: "MaximeLEAUJobeetBundle:Job:search" }
